import sys; sys.path.insert(0, '.')
from PIL import Image, ImageDraw
from defs import B, FIRST_TILE, FIRST_DESC
from art import ART
P='../../'
tile = FIRST_TILE
rows=[]; sheet_h=0; imgs=[]
for b in B:
    im = ART[b[0]](); assert im.size==(b[3]*8,b[4]*8), (b[0],im.size)
    imgs.append((b,im,sheet_h)); sheet_h += b[4]*16
sheet = Image.new('RGBA',(64,sheet_h),(0,0,0,255))
rc = ["","# BEGIN CONCLAND BUILDINGS (ported from ConcLand, MIT, (c) 2026 Leo Kuroshita)",
      "# Generated by gen.py; art is ConcLand 8px art upscaled 2x (or new art in the same style).",
      "# Key tile = (1,1) for 3x3/4x4 buildings, top-left for 1x1/2x2."]
java=[]; status=[]; gui=[]; keys={}
for i,(b,im,y0) in enumerate(imgs):
    name,tool,label,w,h,cost,power,civic,police,com,ind,needp,copter,poll = b
    big = im.resize((w*16,h*16),Image.NEAREST); sheet.paste(big,(0,y0))
    keyoff = (1,1) if w>=3 else (0,0)
    desc = FIRST_DESC+i
    rc.append("# %s (%dx%d)" % (label,w,h))
    for ty in range(h):
        for tx in range(w):
            attrs="(conducts)"
            if (tx,ty)==keyoff:
                keys[name]=tile
                attrs="(zone)(conducts)(building=%dx%d)(behavior=CONCLAND)(description=#%d)" % (w,h,desc)
                if poll: attrs += "(pollution=%d)" % poll
            rc.append("%-5d concland@%d,%d %s" % (tile, tx*16, y0+ty*16, attrs))
            tile+=1
    java.append('\t\tnew Spec(MicropolisTool.%s, (char)%d, %d, %d, %d, %d, %d, %d, %s, %s),' % (tool, keys[name], power, civic, police, com, ind, desc, 'true' if needp else 'false', 'true' if copter else 'false'))
    status.append("zone.%d = %s" % (desc,label))
    icon = tool.lower().replace('cl_','cl')
    gui += ["tool.%s.name = %s" % (tool,label.upper()), "tool.%s.icon = /ic%s.png" % (tool,icon),
            "tool.%s.selected_icon = /ic%shi.png" % (tool,icon), "tool.%s.tip = Build %s ($%d) [ConcLand]" % (tool,label,cost),
            "tool.%s.border = #ff8000" % tool, "tool.%s.bgcolor = rgba(255,128,0,0.375)" % tool]
    # icons
    s = max(1, min(30//im.width, 30//im.height))
    ic = im.resize((im.width*s, im.height*s), Image.NEAREST)
    for hi in (False,True):
        c = Image.new('RGBA',(34,34),(0,0,0,0)); d=ImageDraw.Draw(c)
        d.rectangle([0,0,33,33], fill=(255,210,60,255) if hi else (170,170,170,255), outline=(40,40,40,255))
        c.alpha_composite(ic, ((34-ic.width)//2,(34-ic.height)//2))
        c.save(P+'resources/ic%s%s.png' % (icon,'hi' if hi else ''))
sheet.save(P+'graphics/concland.png')
open('./tiles_rc.txt','w').write("\n".join(rc)+"\n")
open('./java_specs.txt','w').write("\n".join(java)+"\n")
open('./status.txt','w').write("\n".join(status)+"\n")
open('./gui.txt','w').write("\n".join(gui)+"\n")
print("last tile", tile-1, "tools", [b[1] for b in B])
